### ISSUE TITLE
BUG - during installation of junction

### ISSUE THREAD

**Issue by oleg-lukasonok** [teepark/junction#1]
```
pip install junction==2.0.0
```

Gives following error: 

```
Collecting junction==2.0.0
  Using cached junction-2.0.0.tar.gz (47 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      Traceback (most recent call last):
        File "/Users/lego/projects/roche-ni/git-development/ni-adrs-junction/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/lego/projects/roche-ni/git-development/ni-adrs-junction/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/lego/projects/roche-ni/git-development/ni-adrs-junction/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/6l/46tl1kxd14j28xwwl6pzbdlr0000gn/T/pip-build-env-rx9k7ltm/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/6l/46tl1kxd14j28xwwl6pzbdlr0000gn/T/pip-build-env-rx9k7ltm/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/6l/46tl1kxd14j28xwwl6pzbdlr0000gn/T/pip-build-env-rx9k7ltm/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/6l/46tl1kxd14j28xwwl6pzbdlr0000gn/T/pip-build-env-rx9k7ltm/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1322, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 1262, in _find_spec
        File "<frozen importlib._bootstrap_external>", line 1528, in find_spec
        File "<frozen importlib._bootstrap_external>", line 1502, in _get_spec
        File "<frozen zipimport>", line 111, in find_spec
        File "<frozen importlib._bootstrap>", line 675, in spec_from_loader
        File "<frozen importlib._bootstrap_external>", line 822, in spec_from_file_location
        File "<frozen zipimport>", line 170, in get_filename
        File "<frozen zipimport>", line 708, in _get_module_code
        File "<frozen zipimport>", line 637, in _compile_source
        File "paver-minilib.zip/paver/tasks.py", line 69
          print output
          ^^^^^^^^^^^^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by oleg-lukasonok** [comment]
I've used wrong installation command.
